name: build tool and docker container

on:
  push:
    branches-ignore:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build the sources
        run: dotnet publish src/FreqtradeMetaStrategy/FreqtradeMetaStrategy.csproj -r linux-x64 -o .publish -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:ToolName=strategizer --self-contained true --configuration Release -p:InvariantGlobalization=true
        
      - name: Build docker container
        run: docker build .
