name: build tool and push to docker hub

on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Publish
        run: dotnet publish src/FreqtradeMetaStrategy/FreqtradeMetaStrategy.csproj -r linux-x64 -o .publish -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:ToolName=strategizer --self-contained true --configuration Release
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/app:latest